# Prod environment

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./docker/node/prod/Dockerfile
    ports:
      - "3000:3000"
    command: ["npm", "run", "start"]

  frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/node/prod/Dockerfile
    ports:
      - "8000:8000"
    command: ["npm", "run", "start"]
