version: "3.8"

services:
  backend:
    build:
      context: backend/
      dockerfile: docker/node/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npm", "run", "start"]
